name: corsac_jwt
version: 0.1.2
description: Lightweight implementation of JSON Web Tokens (JWT).
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  asn1lib: "^0.5.0"
  logging: "^0.11.3"
  pointycastle: "^1.0.2"
  rsa_pkcs: "^1.1.0"
  crypto: "^2.0.0"

dev_dependencies:
  test: "^1.0.0"
  test_coverage: any
